# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
picture:          '<img class="mypic" src="public/images/me.jpg">'
title:            Vinnie Giarrusso
tagline:          'A Jekyll theme'
description:      'Software Engineer'
url:              http://hyde.getpoole.com

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/vingiarrusso