# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
picture:          '<img class="mypic" src="../public/images/me.jpg">'
title:            Vinnie Giarrusso
tagline:          'San Francisco based Software Engineer'
description:      'Software Engineer'

author:
  name:           'Vinnie Giarrusso'
  url:            http://linkedin.com/in/vinniegiarrusso

paginate:         5

# Custom vars
version:          2.0.0

linkedin:         http://linkedin.com/in/vinniegiarrusso
github:           https://github.com/vingiarrusso
angel:            http://www.angel.co/vingiarrusso